version: '3'
services:
  frontend:
    build: ./nginx
    ports: 
      - "81:80"
    environment: 
      - API_URL=http://35.238.130.34:5000/api/
  backend:
    build: ./backend-algorithmia
    ports: 
      - "5000:5000"
  ai:
    build: ./ai/controller/
    ports:
      - "5001:5000"